[package]
name = "mvp_anvil"
version = "0.1.0"
authors = ["nuhtan <ncrichardson15@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.20"
hematite-nbt = "0.5.2"